[2021-07-07 00:25:31,075] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Spark_S3_ETL.create_emr_cluster 2021-07-07T00:25:27.419789+00:00 [queued]>
[2021-07-07 00:25:31,099] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Spark_S3_ETL.create_emr_cluster 2021-07-07T00:25:27.419789+00:00 [queued]>
[2021-07-07 00:25:31,100] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-07 00:25:31,102] {taskinstance.py:1068} INFO - Starting attempt 1 of 4
[2021-07-07 00:25:31,107] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-07 00:25:31,123] {taskinstance.py:1087} INFO - Executing <Task(EmrCreateJobFlowOperator): create_emr_cluster> on 2021-07-07T00:25:27.419789+00:00
[2021-07-07 00:25:31,137] {standard_task_runner.py:52} INFO - Started process 539 to run task
[2021-07-07 00:25:31,143] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Spark_S3_ETL', 'create_emr_cluster', '2021-07-07T00:25:27.419789+00:00', '--job-id', '164', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmprgckoar5', '--error-file', '/tmp/tmpu1inlqpb']
[2021-07-07 00:25:31,144] {standard_task_runner.py:77} INFO - Job 164: Subtask create_emr_cluster
[2021-07-07 00:25:31,201] {logging_mixin.py:104} INFO - Running <TaskInstance: Spark_S3_ETL.create_emr_cluster 2021-07-07T00:25:27.419789+00:00 [running]> on host 135c51efb9b1
[2021-07-07 00:25:31,329] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=CapstoneProject
AIRFLOW_CTX_DAG_ID=Spark_S3_ETL
AIRFLOW_CTX_TASK_ID=create_emr_cluster
AIRFLOW_CTX_EXECUTION_DATE=2021-07-07T00:25:27.419789+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-07T00:25:27.419789+00:00
[2021-07-07 00:25:31,331] {emr_create_job_flow.py:73} INFO - Creating JobFlow using aws-conn-id: aws_credentials, emr-conn-id: emr_default
[2021-07-07 00:25:31,355] {connection.py:360} ERROR - Failed parsing the json for conn_id emr_default
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 20 (char 19)
[2021-07-07 00:25:31,362] {base_aws.py:368} INFO - Airflow Connection: aws_conn_id=aws_credentials
[2021-07-07 00:25:31,380] {base_aws.py:166} INFO - Credentials retrieved from login
[2021-07-07 00:25:31,382] {base_aws.py:82} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2021-07-07 00:25:31,383] {base_aws.py:87} INFO - Creating session with aws_access_key_id=AKIA3HDBV2JOOPSAIFST region_name=us-east-1
[2021-07-07 00:25:31,410] {base_aws.py:157} INFO - role_arn is None
[2021-07-07 00:25:32,447] {emr_create_job_flow.py:86} INFO - JobFlow with id j-1JMDVUTIE9M7Q created
[2021-07-07 00:25:32,484] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=Spark_S3_ETL, task_id=create_emr_cluster, execution_date=20210707T002527, start_date=20210707T002531, end_date=20210707T002532
[2021-07-07 00:25:32,519] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-07 00:25:32,537] {local_task_job.py:151} INFO - Task exited with return code 0
